# Generated by Django 3.2.9 on 2021-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('ratings', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.TextField(blank=True, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingAgency',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating_agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.TextField(blank=True, null=True)),
                ('actor_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
    ]
