# Generated by Django 3.2.9 on 2021-11-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieactor',
            options={'managed': False},
        ),
    ]
